### PR TITLE
[Platform][Ollama] Support streaming output

### LINKED ISSUE #338: [Platform] Support streaming output for Ollama
Currently, if you set `stream` to `true` when setting Ollama options it will throw an error.

example:
```
$result = $agent->call(
    $messages, [
        'stream' => true,
    ]
);
```
results in:
```
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\JsonException: Syntax error for "http://localhost:11434/api/chat". in /.../vendor/symfony/http-client/Response/CommonResponseTrait.php:90
Stack trace:
#0 /.../vendor/symfony/ai-platform/src/Result/RawHttpResult.php(28): Symfony\Component\HttpClient\Response\AsyncResponse->toArray()
#1 /.../vendor/symfony/ai-platform/src/Bridge/Ollama/OllamaResultConverter.php(47): Symfony\AI\Platform\Result\RawHttpResult->getData()
#2 /.../vendor/symfony/ai-platform/src/Result/ResultPromise.php(48): Symfony\AI\Platform\Bridge\Ollama\OllamaResultConverter->convert()
#3 /.../vendor/symfony/ai-platform/src/Result/ResultPromise.php(37): Symfony\AI\Platform\Result\ResultPromise->await()
#4 /.../vendor/symfony/ai-agent/src/Agent.php(82): Symfony\AI\Platform\Result\ResultPromise->getResult()
#5 /.../src/app.php(26): Symfony\AI\Agent\Agent->call()
#6 {main}
  thrown in /.../vendor/symfony/http-client/Response/CommonResponseTrait.php on line 90
```

### PR DESCRIPTION
**Pull request by logicalor**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| Docs?         | yes/no
| Issues        | Fix #338
| License       | MIT

Both a bug fix and a feature?  Support streaming output from Ollama, preventing an error being thrown if streaming output is sent with the chat request.

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please add an example in examples/ directory? Thanks

**Comment by logicalor** [comment]
> Can you please add an example in examples/ directory? Thanks

@OskarStark updated with an example

**Comment by OskarStark** [comment]
Thanks

It looks like your committer email is not associated with your GitHub account

**Comment by logicalor** [comment]
> Thanks
> 
> It looks like your committer email is not associated with your GitHub account

@OskarStark thanks, hadn't noticed that. Added.

File: src/platform/src/Bridge/Ollama/OllamaMessageChunk.php [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\AI\Platform\Bridge\Ollama;
+
+class OllamaMessageChunk
```
Comment (Guikingone) [inline src/platform/src/Bridge/Ollama/OllamaMessageChunk.php]: Could be `final` and `readonly` maybe?

I'm not sure if the format used by Ollama is shared by OpenAI and others 🤔

Comment (logicalor) [reply src/platform/src/Bridge/Ollama/OllamaMessageChunk.php]: @Guikingone good point re: `final` and `readonly`.  I will update.

Ollama does provide an OpenAI-compatible endpoint at `/v1/chat/completions` (https://ollama.com/blog/openai-compatibility) meaning you would be able to point an OpenAI platform at it and it should work.

This lib is using the native Ollama HTTP API (https://github.com/ollama/ollama/blob/main/docs/api.md).  The chunk format from streaming mode is different to OpenAI's chunk format (https://platform.openai.com/docs/api-reference/chat_streaming/streaming)

File: src/platform/src/Bridge/Ollama/OllamaMessageChunk.php [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+     */
+    public static function fromArray(array $data): self
+    {
+        return new self(
+            $data['model'] ?? '',
+            new \DateTimeImmutable($data['created_at'] ?? ''),
+            $data['message'] ?? [],
+            $data['done'] ?? false
+        );
+    }
```
Comment (Guikingone) [inline src/platform/src/Bridge/Ollama/OllamaMessageChunk.php]: Personal opinion here, if we only use this method once, I don't see the benefits, we could move the `new self...` to the `fromJsonString` method.

File: src/platform/src/Bridge/Ollama/OllamaResultConverter.php [hunk 3]
```diff
@@ -83,4 +92,18 @@ public function doConvertEmbeddings(array $data): ResultInterface
...
+        foreach ((new EventSourceHttpClient())->stream($result) as $chunk) {
+            if ($chunk instanceof FirstChunk || $chunk instanceof LastChunk) {
+                continue;
+            }
+
+            $msg = OllamaMessageChunk::fromJsonString($chunk->getContent());
+            if ($msg) {
+                yield $msg;
+            }
+        }
```
Comment (Guikingone) [inline src/platform/src/Bridge/Ollama/OllamaResultConverter.php:115]: Question for @chr-hertel (not relevant for the review), isn't the same situation that we're facing in #324?

File: src/platform/src/Bridge/Ollama/OllamaMessageChunk.php [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+ *
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\AI\Platform\Bridge\Ollama;
+
+final readonly class OllamaMessageChunk
```
Comment (Guikingone) [inline src/platform/src/Bridge/Ollama/OllamaMessageChunk.php:17]: BTW, do not forget to add your informations here as author.

File: src/platform/src/Bridge/Ollama/OllamaMessageChunk.php (hunk 2 above)
Comment (logicalor) [reply src/platform/src/Bridge/Ollama/OllamaMessageChunk.php]: @Guikingone thanks, I agree - I've removed the method and put the logic into `fromJsonString`.

File: src/platform/src/Bridge/Ollama/OllamaMessageChunk.php (hunk 4 above)
Comment (logicalor) [reply src/platform/src/Bridge/Ollama/OllamaMessageChunk.php:17]: Updated 🙏

File: src/platform/src/Bridge/Ollama/OllamaResultConverter.php (hunk 3 above)
Comment (chr-hertel) [reply src/platform/src/Bridge/Ollama/OllamaResultConverter.php:115]: It's not since this is only working on the response in the ResultConverter, which is only called when finally fetching the content. In #324 the `stream` is called already in the client

File: examples/ollama/chat-ollama-streaming.php [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+    Message::ofUser('Tina has one brother and one sister. How many sisters do Tina\'s siblings have?'),
+);
+
+// Stream the response
+$result = $agent->call($messages, ['stream' => true]);
+
+// Emit each chunk as it is received
+foreach ($result as $chunk) {
+    echo $chunk->getContent();
+}
```
Comment (chr-hertel) [inline examples/ollama/chat-ollama-streaming.php]:
```suggestion
}
echo \PHP_EOL;
```

File: examples/ollama/chat-ollama-streaming.php
Comment (chr-hertel) [inline examples/ollama/chat-ollama-streaming.php:1]: Let's call the file only `stream.php` - it is more consistent with the other stream examples, and `ollama` is basically the folder already

**Comment by chr-hertel** [comment]
which ollama version do you use?
image

File: src/platform/src/Bridge/Ollama/OllamaMessageChunk.php [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+        // Return the assistant's message content if available
+        return $this->message['content'] ?? '';
+    }
+
+    public static function fromJsonString(string $json): ?self
+    {
+        $data = json_decode($json, true);
+        if (!\is_array($data)) {
+            return null;
+        }
```
Comment (chr-hertel) [inline src/platform/src/Bridge/Ollama/OllamaMessageChunk.php]: please move this to the result converter - it's their job to convert to data. fine with having the value object, but let's keep it simple than :+1:

**Review by chr-hertel — CHANGES_REQUESTED** [review]
Thanks @logicalor for reporting and working on this - we need this :)

Made some comments, but i think all in all we're close to merging it :+1:

File: src/platform/src/Bridge/Ollama/OllamaMessageChunk.php (hunk 6 above)
Comment (logicalor) [reply src/platform/src/Bridge/Ollama/OllamaMessageChunk.php]: @chr-hertel I have removed the fromJsonString method and put the logic into `OllamaResultConverter::convertStream` instead.

**Comment by logicalor** [comment]
> which ollama version do you use?

@chr-hertel I was running `0.10.1` but just upgraded to `0.11.7`.

File: examples/ollama/chat-ollama-streaming.php
Comment (logicalor) [reply examples/ollama/chat-ollama-streaming.php:1]: Updated 👍

**Review by chr-hertel — APPROVED** [review]
Works & looks good :+1:

**Comment by chr-hertel** [comment]
Thank you @logicalor.

**Comment by logicalor** [comment]
> Thank you @logicalor.

🙏
