### PR TITLE
[Agent][Platform][OpenAI] Add stream usage support

### LINKED ISSUE #753: [Agent][Platform][OpenAI] Add support to include usage on streams
Hi !  

OpenAI GPT added a functionality to receive the usage token using stream https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options-include_usage.

The current implementation just ignore these messages as is not part of the delta content.  https://github.com/symfony/ai/blob/2c4d20d7b2865e0772ce03069542fbb9e0da478b/src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php#L110

I’ve been working on an [implementation](https://github.com/symfony/ai/pull/754) to parse and return the usage object through the generator, but I’m not really sure if this is the best approach. Alternatively, I could consider using an event listener or adding a usage property in the StreamResult that would be accessible after the stream has been consumed.

So far, this is how the PR looks in action:

```php
$options = [
    'stream' => true,
    'stream_options' => [
        'include_usage' => true,
    ],
];

$stream = $agent->call($messages, $options)->getContent();

if (!is_iterable($stream)) {
    throw new \RuntimeException('Invalid result type, expected iterable');
}

foreach ($stream as $chunk) {
    if (is_string($chunk)) {
        $context->setDelta($chunk);
        continue;
    }

    if ($chunk instanceof TokenUsage) {
        $context->addUsedTokens(
            $chunk->totalTokens ?: 0,
            $chunk->cachedTokens ?: 0
        );
    }
}
```

I'll be so glad to know your opinion about these approaches or any other alternatives.

Thanks !

### PR DESCRIPTION
**Pull request by oesteve**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Docs?         | no
| Issues        | Fix #753
| License       | MIT

```php

$result = $agent->call($messages, [
    'stream' => true,
]);

foreach ($result->getContent() as $textChunk) {
    echo $textChunk;
}

print_token_usage($result->getMetadata()->get('token_usage'));
```

### CODE REVIEW

File: examples/openai/toolcall-stream-with-usage.php [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+
+// Output text chunks
+/** @var TextChunk $textChunk */
+foreach ($result->getContent() as $textChunk) {
+
+    // $textChunk implement \Stringable
+    echo $textChunk->getContent();
+
+    // Chunk also contain metadata
+    // $textChunk->getMetadata()->get('id'); // Stream id
```
Comment (OskarStark) [inline examples/openai/toolcall-stream-with-usage.php]: remove?

File: examples/openai/toolcall-stream-with-usage.php [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    'stream_options' => [
+        'include_usage' => true, // include usage in the response
+    ],
+]);
+
+// Output text chunks
+/** @var TextChunk $textChunk */
+foreach ($result->getContent() as $textChunk) {
+
+    // $textChunk implement \Stringable
```
Comment (OskarStark) [inline examples/openai/toolcall-stream-with-usage.php]: remove

File: examples/openai/toolcall-stream-with-usage.php [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+
+$clock = new Clock();
+$openMeteo = new OpenMeteo(http_client());
+$toolbox = new Toolbox([$clock, $openMeteo], logger: logger());
+$processor = new AgentProcessor($toolbox);
+
+$tokenOutputProcessor = new TokenOutputProcessor();
+
+$agent = new Agent($platform, 'gpt-4o-mini', [$processor], [$processor]);
+$messages = new MessageBag(Message::ofUser(<<<TXT
```
Comment (OskarStark) [inline examples/openai/toolcall-stream-with-usage.php]: why a multiline text here?

File: examples/openai/toolcall-stream-with-usage.php [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+    Tell me the time and the weather in Dublin.
+    TXT));
+$result = $agent->call($messages, [
+    'stream' => true, // enable streaming of response text
+    'stream_options' => [
+        'include_usage' => true, // include usage in the response
+    ],
+]);
+
+// Output text chunks
```
Comment (OskarStark) [inline examples/openai/toolcall-stream-with-usage.php]:
```suggestion

```

File: src/agent/src/Toolbox/AgentProcessor.php [hunk 5]
```diff
@@ -76,19 +76,24 @@ public function processInput(Input $input): void
...
-        if ($output->getResult() instanceof GenericStreamResponse) {
+        $result = $output->getResult();
+
+        if ($result instanceof GenericStreamResponse) {
             $output->setResult(
-                new ToolboxStreamResponse($output->getResult()->getContent(), $this->handleToolCallsCallback($output))
+                new ToolboxStreamResponse(
+                    $result,
+                    $this->handleToolCallsCallback($output)
+                )
```
Comment (OskarStark) [inline src/agent/src/Toolbox/AgentProcessor.php:86]: lets keep one line

File: examples/openai/toolcall-stream-with-usage.php [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+require_once dirname(__DIR__).'/bootstrap.php';
+
+$platform = PlatformFactory::create(env('OPENAI_API_KEY'), http_client());
+
+$clock = new Clock();
+$openMeteo = new OpenMeteo(http_client());
+$toolbox = new Toolbox([$clock, $openMeteo], logger: logger());
+$processor = new AgentProcessor($toolbox);
+
+$tokenOutputProcessor = new TokenOutputProcessor();
```
Comment (OskarStark) [inline examples/openai/toolcall-stream-with-usage.php]: is it used?

Comment (oesteve) [reply examples/openai/toolcall-stream-with-usage.php]: It was not

File: examples/openai/toolcall-stream-with-usage.php (hunk 3 above)
Comment (oesteve) [reply examples/openai/toolcall-stream-with-usage.php]: It made sense at some point, but it doesn't anymore.

**Comment by oesteve** [comment]
@chr-hertel , thanks for the feedback. Your approach with `TokenUsageAggregation` looks much cleaner and allows for the reuse of `token_usage`. 

On the other side, the `TokenOutputProcessor` works well with regular results, but I can’t see how to make an `OutputProcessorInterface` work with streams. The usage is received at the end of the stream after the `processOutput` has been called.

**Comment by chr-hertel** [comment]
Yeah, makes sense - that looks tricky - you needed to do the metadata handling at various places.
Can we go for some kind of middle way tho - maybe skipping the processor but dropping that extra option (is it interpreted anyways?) and provide an aggregated object as `token_usage` on high level for the devs?

**Comment by OskarStark** [comment]
open to finish this PR @oesteve ?

**Comment by oesteve** [comment]
@OskarStark  Yes, I'd like to get back to this. I'll have some free time this season to make the changes. If it's a priority for you and you want to open an alternative PR, that's fine to me.

**Comment by oesteve** [comment]
@OskarStark @chr-hertel Finally, I had some time to come back to this. I've practically rewritten the PR. I hope this approach is interesting for you. What do you think?

I also have some doubts about whether the example provides real value or just noise, since the approach is quite similar for the non-stream calls.

**Review by chr-hertel — CHANGES_REQUESTED** [review]
Looks like with `.ai` and `.idea` some unintended folders got commited with rebase

File: examples/openai/stream-token-metadata.php
Comment (chr-hertel) [inline examples/openai/stream-token-metadata.php:1]: Works well :+1:

File: src/agent/src/Toolbox/AgentProcessor.php [hunk 7]
```diff
@@ -79,12 +79,7 @@ public function processOutput(Output $output): void
         $result = $output->getResult();
 
         if ($result instanceof GenericStreamResponse) {
-            $output->setResult(
-                new ToolboxStreamResponse(
-                    $result->getContent(),
-                    fn (ToolCallResult $result, ?AssistantMessage $streamedAssistantResponse = null) => $this->handleToolCallsCallback($output, $result, $streamedAssistantResponse)
-                )
-            );
+            $output->setResult(new ToolboxStreamResponse($result, fn (ToolCallResult $result, ?AssistantMessage $streamedAssistantResponse = null) => $this->handleToolCallsCallback($output, $result, $streamedAssistantResponse)));
```
Comment (chr-hertel) [inline src/agent/src/Toolbox/AgentProcessor.php]: change is unrelated, right? in that case please revert to keep the diff small :+1:

File: src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php [hunk 8]
```diff
@@ -71,7 +72,9 @@ public function convert(RawResultInterface|RawHttpResult $result, array $options
         }
 
         if ($options['stream'] ?? false) {
-            return new StreamResult($this->convertStream($result));
+            $streamResult = new StreamResult($this->convertStream($result, $streamResult));
+
+            return $streamResult;
```
Comment (chr-hertel) [inline src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php:78]: that kind of binding is pretty much mind bending, but i currently have no better idea

Comment (chr-hertel) [reply src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php:78]: we should at least comment what is happening here

File: src/agent/src/Toolbox/StreamResult.php
Comment (chr-hertel) [inline src/agent/src/Toolbox/StreamResult.php:1]: i wonder if this is too late and should happen directly after conversion - we won't propagate the metadata for usage without agent and toolbox then, right?

**Review by chr-hertel — CHANGES_REQUESTED** [review]
Thanks for wrapping your head around this - though nut :pray: - left some comments, but this is on a good track, thanks again!

File: src/agent/src/Toolbox/AgentProcessor.php (hunk 7 above)
Comment (oesteve) [reply src/agent/src/Toolbox/AgentProcessor.php]: Subtle, but it is. Maybe I didn’t fully catch @OskarStark 's [comment](https://github.com/symfony/ai/pull/754#discussion_r2573126312). 

I kept the previous indention.

File: src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php (hunk 8 above)
Comment (oesteve) [reply src/platform/src/Bridge/OpenAi/Gpt/ResultConverter.php:78]: Yes it really is. Another approach that came to my mind was to yield the TokenUsage and propagate to the metadata in the StreamResult

```php
namespace Symfony\AI\Platform\Result;

final class StreamResult extends BaseResult
{
    public function getContent(): \Generator
    {
        foreach ($this->generator as $chunk) {
            if ($chunk instanceof TokenUsageInterface) {
                $this->getMetadata()->add('token_usage', $chunk);
                continue;
            }

            yield $chunk;
        }
    }
}
```

That makes this approach available for all providers, but honestly, I don't know if this is a good or bad approach.

File: src/agent/src/Toolbox/StreamResult.php
Comment (oesteve) [reply src/agent/src/Toolbox/StreamResult.php:1]: I'm not sure I understood your comment. This is the earliest point I found at the Agent level. Do you have a better approach in mind?

At the platform level, the result includes the metadata along with the propagated usage.

https://github.com/oesteve/ai/blob/0497a1951f0428ff7f951b4469a3175bbe5ac70a/src/platform/src/Bridge/OpenAi/Tests/Gpt/ResultConverterTest.php#L222

**Comment by oesteve** [comment]
Thank you for your comments, being able to contribute is truly inspiring 🙂

**Comment by chr-hertel** [comment]
Hi @oesteve, your work, especially the your comment about handling the cases while streaming, solved it for me:

this snippet:
```php
        foreach ($this->generator as $chunk) {
            if ($chunk instanceof TokenUsageInterface) {
                $this->getMetadata()->add('token_usage', $chunk);
                continue;
            }

            yield $chunk;
        }
```

in the end became: https://github.com/oesteve/ai/compare/main...chr-hertel:ai:stream-listener
(not completely done yet, but i'm quite happy how that transforms the issue, and makes it easier managable for tokens and toolcalls)

---

So much about "truly inspiring" - thanks for that! :pray:

**Comment by oesteve** [comment]
@chr-hertel, that looks really promising. An event-driven interface add more flexiblility from my point of view.

It would be great to have access from the Agent layer to add a listener and receive Platform events. 

I'm not really sure in which direction the Agent component is going ... but implementing certain uncommon use cases like this requires forking and sending a PR. Access to these low-level events enables external implementation and simplifies the Agent logic.

One last thought, could it make sense to be close to symfony/event-dispatcher-contracts?

**Comment by chr-hertel** [comment]
@oesteve yea, thought about the EventDispatcher interface, but was a bit reluctant - injecting the dispatcher to the stream would also add a larger service dependency. maybe it's a rather small step, but i feels dangerous to enable easy container integration since the stream is something quite easy to break and performance sensitive ... but maybe that's only a documentation concern and provide users with the freedom to shoot themselves in the foot :grimacing: 

anyhow, that could be an easy follow-up. will wrap that up, merge your work and mine as follow up :+1:

**Comment by chr-hertel** [comment]
Thank you @oesteve.
