### PR TITLE
[Store][InMemory] Fix cosine similarity sorting

### LINKED ISSUE #187: [Store] Incorrect Similarity Sorting in `InMemoryStore` for Cosine Similarity
### Description

The `InMemoryStore::query()` method currently sorts all similarity strategies using the same logic: ascending order of the calculated "distance". This works well for distance-based strategies like Euclidean or Manhattan, but it results in **incorrect ordering for Cosine Similarity**, which returns higher values for more relevant matches (e.g., 0.9 is *more* similar than 0.3).

### Problem
We set the distance as cosine similarity using:
```php
 'distance' => $strategy($vectorDocument, $vector),
// for cosineStrategy will be 
'distance' => $this->cosineSimilarity($doc, $query)
```

Then the following logic is used across all strategies:

```php
...
usort($currentEmbeddings, fn ($a, $b) => $a['distance'] <=> $b['distance']);
```

For cosine similarity, this is incorrect, as it ranks lower values first (less similar), which is the opposite of what is intended.

### Steps to Reproduce:

1. Create an `InMemoryStore`  instance configured with `self::COSINE_SIMILARITY`
2.  Add several `VectorDocument` instances to the store with varying degrees of similarity to a potential query vector.
3. Perform a `query()` with a target Vector. 
4. Observe the order of the returned VectorDocument objects.

### Expected Behavior:
The VectorDocument instances should be sorted in descending order of their cosine similarity scores (i.e., the most similar documents appear at the beginning of the returned array).

### Actual Behavior:
The VectorDocument instances are sorted in ascending order of their cosine similarity scores (i.e., the least similar documents appear at the beginning of the returned array). This is due to the generic usort comparison `$embedding['distance'] <=> $nextEmbedding['distance']` which implicitly sorts in ascending order.

### Proposed Solution
Normalize cosine similarity as a distance by converting it to a distance with this common conversion:

```php
return 1 - cosineSimilarity(...);
```

This would unify the behavior across all strategies, allowing consistent sorting and interpretation:

- Cosine similarity score (0.0 to 1.0) → distance (0.0 best, 1.0 worst)
- Works with the current usort logic
- Eliminates the need for conditional sorting logic per strategy

### PR DESCRIPTION
**Pull request by RamyHakam**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| Docs?         | no 
| Issues        | Fix #187 ... 
| License       | MIT

This PR fixes #187, the issue where cosine similarity values were incorrectly treated as distances in the InMemoryStore::query() method, resulting in reversed result ordering. 

The fix converts cosine similarity to distance using `1-similarity`, which is the common conversion between similarity and distance.

 Ensuring consistent sorting behavior across all strategies. Includes updated unit tests to validate.

### CODE REVIEW

File: src/store/src/InMemoryStore.php [hunk 1]
```diff
@@ -49,7 +49,7 @@ public function add(VectorDocument ...$documents): void
     public function query(Vector $vector, array $options = [], ?float $minScore = null): array
     {
         $strategy = match ($this->similarity) {
-            self::COSINE_SIMILARITY => $this->cosineSimilarity(...),
+            self::COSINE_DISTANCE => $this->cosineDistance(...),
```
Comment (OskarStark) [inline src/store/src/InMemoryStore.php:52]: Now we have cosine distance and cosine similarity but only one constant?

File: src/store/src/InMemoryStore.php [hunk 2]
```diff
@@ -80,6 +80,11 @@ public function query(Vector $vector, array $options = [], ?float $minScore = nu
         );
     }
 
+    private function cosineDistance(VectorDocument $embedding, Vector $against): float
+    {
+        return 1 - $this->cosineSimilarity(...);
+    }
+
     private function cosineSimilarity(VectorDocument $embedding, Vector $against): float
```
Comment (OskarStark) [inline src/store/src/InMemoryStore.php:88]: I would remove this method and move the body to the cosineDistance method

File: src/store/src/InMemoryStore.php [hunk 3]
```diff
@@ -20,7 +20,7 @@
  */
 final class InMemoryStore implements VectorStoreInterface
 {
-    public const COSINE_SIMILARITY = 'cosine';
+    public const COSINE_DISTANCE = 'cosine';
```
Comment (OskarStark) [inline src/store/src/InMemoryStore.php:23]: So we really need to rename this constant? This makes this PR a BC break

File: src/store/src/InMemoryStore.php (hunk 2 above)
Comment (RamyHakam) [reply src/store/src/InMemoryStore.php:88]: We still need to calculate `cosineSimilarity()` internally for both `cosineDistance` and `angularDistance` since angular distance is defined as `acos(cosineSimilarity) / π`.

File: src/store/src/InMemoryStore.php (hunk 3 above)
Comment (RamyHakam) [reply src/store/src/InMemoryStore.php:23]: I believe we should rename it because the expected result sorting differs between similarity and distance: 
similarity is typically sorted descending (higher is better), while distance is sorted ascending (lower is better).

Also, Since all other metrics use distance,  I think unifying the strategy for consistency and clarity makes sense.

File: src/store/src/InMemoryStore.php (hunk 1 above)
Comment (RamyHakam) [reply src/store/src/InMemoryStore.php:52]: Renamed to distanceMetric to reduce confusion and reflect that all strategies use distance, not similarity.

File: src/store/src/InMemoryStore.php (hunk 2 above)
Comment (OskarStark) [reply src/store/src/InMemoryStore.php:88]: Got it thanks

File: src/store/src/InMemoryStore.php (hunk 3 above)
Comment (OskarStark) [reply src/store/src/InMemoryStore.php:23]: Ok fine then

File: src/store/src/InMemoryStore.php [hunk 4]
```diff
@@ -48,18 +48,18 @@ public function add(VectorDocument ...$documents): void
...
-        $strategy = match ($this->similarity) {
-            self::COSINE_SIMILARITY => $this->cosineSimilarity(...),
+        $distanceMetricStrategy = match ($this->distanceMetric) {
+            self::COSINE_DISTANCE => $this->cosineDistance(...),
             self::ANGULAR_DISTANCE => $this->angularDistance(...),
             self::EUCLIDEAN_DISTANCE => $this->euclideanDistance(...),
             self::MANHATTAN_DISTANCE => $this->manhattanDistance(...),
             self::CHEBYSHEV_DISTANCE => $this->chebyshevDistance(...),
-            default => throw new InvalidArgumentException(\sprintf('Unsupported similarity strategy "%s"', $this->similarity)),
+            default => throw new InvalidArgumentException(\sprintf('Unsupported Distance metric "%s"', $this->distanceMetric)),
```
Comment (OskarStark) [inline src/store/src/InMemoryStore.php]:
```suggestion
            default => throw new InvalidArgumentException(\sprintf('Unsupported distance metric "%s"', $this->distanceMetric)),
```

File: src/store/src/InMemoryStore.php [hunk 5]
```diff
@@ -48,18 +48,18 @@ public function add(VectorDocument ...$documents): void
      */
     public function query(Vector $vector, array $options = [], ?float $minScore = null): array
     {
-        $strategy = match ($this->similarity) {
-            self::COSINE_SIMILARITY => $this->cosineSimilarity(...),
+        $distanceMetricStrategy = match ($this->distanceMetric) {
```
Comment (OskarStark) [inline src/store/src/InMemoryStore.php]:
```suggestion
        $strategy = match ($this->distanceMetric) {
```

no need to rename I guess

File: src/store/src/InMemoryStore.php [hunk 6]
```diff
@@ -32,7 +32,7 @@ final class InMemoryStore implements VectorStoreInterface
     private array $documents = [];
 
     public function __construct(
-        private readonly string $similarity = self::COSINE_SIMILARITY,
+        private readonly string $distanceMetric = self::COSINE_DISTANCE,
```
Comment (OskarStark) [inline src/store/src/InMemoryStore.php]:
```suggestion
        private readonly string $distance = self::COSINE_DISTANCE,
```

**Comment by chr-hertel** [comment]
Makes sense to you @Guikingone?

**Comment by Guikingone** [comment]
Yep, small mistake on my side, nice catch @RamyHakam 👍🏻

**Review by chr-hertel — APPROVED** [review]

**Comment by chr-hertel** [comment]
Thank you @RamyHakam.
