### PR TITLE
[AI Bundle][Platform] Fix Anthropic platform definition

### LINKED ISSUE #363: Invalid constructor argument 3 for service "ai.platform.anthropic": argument 2 must be defined before in dev-main
Bug Report

  Environment:
  - symfony/ai-bundle: dev-main (installed from git on 2025-08-25)
  - Symfony: 7.3
  - PHP: 8.3
  - Platform: Docker with FrankenPHP

  Issue:
  When configuring Anthropic agents in ai.yaml, the application fails to clear cache and throws a service definition error.

  Error Message:
  In DefinitionErrorExceptionPass.php line 48:
  Invalid constructor argument 3 for service "ai.platform.anthropic": argument 2 must be defined before. Check your service definition.

  Configuration Used:
```yaml
  ai:
      platform:
          anthropic:
              api_key: '%env(ANTHROPIC_API_KEY)%'

      agent:
          blog_generator:
              platform: 'ai.platform.anthropic'
              model:
                  class: 'Symfony\AI\Platform\Bridge\Anthropic\Claude'
                  name: !php/const Symfony\AI\Platform\Bridge\Anthropic\Claude::SONNET_35
              system_prompt: "Tu es un rédacteur web expert."
```

  Steps to Reproduce:
  1. Install symfony/ai-bundle from dev-main
  2. Configure Anthropic platform with valid API key
  3. Configure at least one agent using Anthropic Claude models
  4. Run symfony console cache:clear

  Expected Behavior:
  Cache should clear successfully and Anthropic agents should be available.

  Actual Behavior:
  Cache clear fails with service definition error related to constructor arguments.

  Additional Context:
  - Mistral configuration works perfectly with the same setup
  - The error suggests an issue with the service definition in the Anthropic bridge
  - This prevents using Anthropic agents entirely
  - Switching to Mistral platform works as expected

  Workaround:
  Currently using Mistral as alternative, but Anthropic support is needed for production requirements.

  Service Definition Debug:
  The error seems to indicate that the ai.platform.anthropic service has incorrect constructor argument ordering or missing dependencies.

  Would appreciate guidance on:
  1. Is this a known issue with dev-main?
  2. Are there specific configuration requirements for Anthropic not documented?
  3. Is there a fix or workaround available?

### PR DESCRIPTION
**Pull request by VincentLanglet**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Docs?         | no 
| Issues        | Fix #363
| License       | MIT

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@Krystopher88 could you try this and confirm it solves your issue ?

File: src/platform/src/Bridge/Anthropic/ModelClient.php [hunk 1]
```diff
@@ -27,7 +27,7 @@
     public function __construct(
         HttpClientInterface $httpClient,
         #[\SensitiveParameter] private string $apiKey,
-        private string $version = '2023-06-01',
+        private ?string $version = null,
```
Comment (OskarStark) [inline src/platform/src/Bridge/Anthropic/ModelClient.php]: Why this change?

File: src/platform/src/Bridge/Anthropic/PlatformFactory.php [hunk 2]
```diff
@@ -25,7 +25,7 @@
     public static function create(
         #[\SensitiveParameter]
         string $apiKey,
-        string $version = '2023-06-01',
+        ?string $version = null,
```
Comment (xabbuh) [inline src/platform/src/Bridge/Anthropic/PlatformFactory.php]: What about moving this parameter at the end instead?

File: src/platform/src/Bridge/Anthropic/ModelClient.php (hunk 1 above)
Comment (VincentLanglet) [reply src/platform/src/Bridge/Anthropic/ModelClient.php]: Platform is doing 
```
new ModelClient($httpClient, $apiKey, $version)
```

Which means that, either
- It has to know the default value, so `$version = '2023-06-01',` is duplicated
- It requires the logic 
```
null === $version ? new ModelClient($httpClient, $apiKey) : new ModelClient($httpClient, $apiKey, $version);
```

Also, since I needed to pass the platform version in the AiBundle config, I didn't want to pass 
```
$platform['version'] ?? '2023-06-01',
```
with the version hard coded a third time.

File: src/platform/src/Bridge/Anthropic/PlatformFactory.php (hunk 2 above)
Comment (VincentLanglet) [reply src/platform/src/Bridge/Anthropic/PlatformFactory.php]: Might be a solution.

But still I'm unsure it a nice pattern to duplicate the default value `'2023-06-01'` between the factory and the Model, no ?

**Review by chr-hertel — CHANGES_REQUESTED** [review]
Thanks for jumping on that @VincentLanglet!
I'm usually not a huge fan of nullable arguments, and it's true that this is a bit weird in handling and duplicated here.

One thing I noticed when looking at the Anthropics docs again: there are only two version strings at this point `2023-01-01` and the `2023-06-01` we're currently using. and guess what, only one is supported by our implementation here anyways. with `2023-01-01` you get the error "anthropic-version: "2023-01-01" not allowed for this endpoint" error.

So, if you're up for it, let's just clean that up, remove all arguments, the bundle config option and hard code the version in the header: `'anthropic-version' => '2023-06-01'` - easier and we don't have to debate the nullable and where not to duplicate stuff :laughing:

**Comment by OskarStark** [comment]
Please fix PHPStan, thanks

**Comment by OskarStark** [comment]
Thanks for fixing this bug Vincent.

**Comment by chr-hertel** [comment]
@OskarStark saw my comment? any thoughts on that?

**Comment by OskarStark** [comment]
You mean regarding the defaults? Mixed feelings, as if there is a new version, you can only use it with a new release of the lib, like for the models
