### PR TITLE
[Platform][Gemini] Fix choice conversion logic for `executableCode` and `codeExecutionResult`

### LINKED ISSUE #422: RuntimeException: Unsupported finish reason "STOP" in ResultConverter (Gemini bridge)
Describe the bug 🎯

When using the Symfony AI Platform with Gemini, a fatal error occurs if the model response contains the finish reason "STOP".

Instead of being handled gracefully, it triggers a RuntimeException:

PHP Fatal error: Uncaught Symfony\AI\Platform\Exception\RuntimeException: Unsupported finish reason "STOP".
in vendor/symfony/ai-platform/src/Bridge/Gemini/Gemini/ResultConverter.php:130

Expected behavior ✅
- No exception should be thrown in this case.

Actual behavior 🐛
- "STOP" is not supported in ResultConverter.
- This leads to a fatal error and crashes the application.

Steps to reproduce 🔄
- Call Gemini through the Symfony AI Platform with code_execution server tool enabled.
- Receive a response where finishReason = "STOP".
- The error occurs inside ResultConverter->convertChoice().

Error log 📋
```
Uncaught Symfony\AI\Platform\Exception\RuntimeException: Unsupported finish reason "STOP".
in vendor/symfony/ai-platform/src/Bridge/Gemini/Gemini/ResultConverter.php:130
Stack trace:
#0 ResultConverter->convertChoice()
#1 ResultConverter->convert()
#2 ResultPromise->await()
#3 Agent->call()
#4 Program->__invoke()
```

Environment 🌍
AI Platform version: latest (from main)
Gemini model: 2.5 Pro
PHP version: 8.4

### PR DESCRIPTION
**Pull request by pentiminax**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Docs?         | no
| Issues        | Fix #422
| License       | MIT

This PR fixes a crash in the **Gemini** ResultConverter when handling responses that only contained executableCode and codeExecutionResult parts.

Before: 
- RuntimeException: Unsupported finish reason "STOP"

After:
- Proper conversion into a TextResult containing formatted code blocks and the last successful OUTCOME_OK output.
- No more exceptions for valid Gemini responses.

What’s Changed
- Enhanced choice conversion logic in ResultConverter::convertChoice():
- Single part → keep legacy behavior (functionCall, text, or one code/output part).
- Multiple parts → aggregate:
- executableCode → Markdown code blocks.
- codeExecutionResult (OUTCOME_OK) → output block.
- Parts flagged as thought: true are ignored for text/code, but their successful execution results are preserved.

New unit tests:
- Covers the failing payload where all parts were marked thought: true.
- Ensures the result is a readable TextResult instead of an exception.

Why
- Prevents crashes when Gemini outputs reasoning steps as thought: true.
- Keeps only useful information (code + last valid output).
- Maintains backward compatibility for simpler responses.

Impact
- No BC breaks — existing behavior for single-part responses unchanged.
- Improved UX — users now see clean Markdown code + output instead of runtime errors.

### CODE REVIEW

File: src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+        $this->assertTrue(
+            strpos($content, 'from collections import Counter') < strpos($content, "{'est': 3, 'symfony': 2"),
+            'Le code Python devrait apparaître avant la sortie OUTCOME_OK.'
+        );
+    }
+
+    private function getGeminiStub(): string
+    {
+        return <<<'JSON'
+{
```
Comment (OskarStark) [inline src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php]: Lets make this a fixture file please

**Comment by OskarStark** [comment]
friendly ping @valtzu

File: src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+
+        $this->assertStringContainsString('```', $content);
+        $this->assertStringContainsString('from collections import Counter', $content);
+
+        $this->assertStringContainsString("{'est': 3, 'symfony': 2, 'un': 2, 'php': 2", $content);
+
+        $this->assertNotEmpty($content);
+        $this->assertTrue(
+            strpos($content, 'from collections import Counter') < strpos($content, "{'est': 3, 'symfony': 2"),
+            'Le code Python devrait apparaître avant la sortie OUTCOME_OK.'
```
[the remark this answers is not in the document]
Comment (OskarStark) [reply src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php]: This is ok, as its a fixture

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php [hunk 3]
```diff
@@ -110,26 +110,58 @@ private function convertStream(HttpResponse $result): \Generator
...
         }
 
-        if (isset($contentPart['text'])) {
-            return new TextResult($contentPart['text']);
+        $content = '';
+
+        foreach ($contentParts as $contentPart) {
+            if (isset($contentPart['executableCode']['code'])) {
+                $code = $contentPart['executableCode']['code'];
+                $content .= $code;
```
[the remark this answers is not in the document]
Comment (OskarStark) [reply src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: Sounds reasonable, WDYT @pentiminax

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php [hunk 4]
```diff
@@ -110,26 +110,58 @@ private function convertStream(HttpResponse $result): \Generator
...
+            }
+
+            if (isset($contentPart['codeExecutionResult']['outcome'], $contentPart['codeExecutionResult']['output']) && $contentPart['codeExecutionResult']['outcome'] === 'OUTCOME_OK') {
```
[the remark this answers is not in the document]
Comment (OskarStark) [reply src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: Up to you

File: src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php (hunk 1 above)
Comment (pentiminax) [reply src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php]: Sure

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (pentiminax) [reply src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: Absolutly!

File: src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+#[CoversClass(ResultConverter::class)]
+#[Small]
+#[UsesClass(TextResult::class)]
+#[UsesClass(RawHttpResult::class)]
+final class ResultConverterTest extends TestCase
+{
+    public function testItAggregatesExecutableCodeAndOutputsEvenWhenAllPartsAreThought()
+    {
+        $response = $this->createStub(ResponseInterface::class);
+        $responseContent = file_get_contents(\dirname(__DIR__, 6).'/fixtures/Bridge/Gemini/CodeExecution/gemini_code_execution_ok.json');
```
Comment (OskarStark) [inline src/platform/tests/Bridge/Gemini/CodeExecution/ResultConverterTest.php]:
```suggestion
        $responseContent = file_get_contents(\dirname(__DIR__, 6).'/fixtures/Bridge/Gemini/gemini_code_execution_ok.json');
```
Should be enough I guess

File: fixtures/Bridge/Gemini/CodeExecution/gemini_code_execution_ok.json [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+                        },
+                        "thought": true
+                    },
+                    {
+                        "codeExecutionResult": {
```
Comment (OskarStark) [inline fixtures/Bridge/Gemini/CodeExecution/gemini_code_execution_ok.json]: So this response contains 2 failed and one OK?

Comment (pentiminax) [reply fixtures/Bridge/Gemini/CodeExecution/gemini_code_execution_ok.json]: Yes, this response matches the requested prompt:

'Count how many times each word appears in this text using the Python code execution tool:
"Symfony est un framework PHP. Symfony est utilisé dans de nombreux projets. PHP est un langage puissant."
Display the result as a dictionary sorted by frequency, then explain the result.'

It seems Gemini iteratively fixed its code until it executed correctly.

File: fixtures/Bridge/Gemini/gemini_code_execution_ok.json
Comment (OskarStark) [inline fixtures/Bridge/Gemini/gemini_code_execution_ok.json:1]: so would be good to have a fixture (and test) for failed, too

**Comment by pentiminax** [comment]
For information: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/code-execution-api

File: fixtures/Bridge/Gemini/gemini_code_execution_ok.json
Comment (pentiminax) [reply fixtures/Bridge/Gemini/gemini_code_execution_ok.json:1]: Finally, I removed the `isSuccessfulCodeExecution ` condition, we want to display all the LLM’s thoughts to the user, right?"

**Comment by valtzu** [comment]
First of all, thanks for working on this – when the `server_tools` were implemented, I only ever tested `google_search` and `url_context`.

In my opinion the output should not contain the generated & executed code by default, since the last message/`part` is a human readable message which already contains the answer to the asked question.

The `code_execution` is a server tool, like `google_search` or `url_context`, and those don't show up in the output either – even though f.e. search results / "sources" are available as `"grounding"` in the response.

---

If I'm building a customer-facing chat bot which should be able to answer to `Calculate 20th fibonacci number. Then find the nearest palindrome to it.` (an example from the `code_execution` docs), I don't think the customer should see the python code.

---

Somewhere we have this feature: `keepToolMessages`. Maybe we could even use that, or add a new one, like `keepServerToolParts` to control if those will be included or not :thinking:

File: fixtures/Bridge/Gemini/code_execution_outcome_ok.json [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+                    {
+                        "executableCode": {
+                            "language": "PYTHON",
+                            "code": "from collections import Counter\\nimport re\\n\\n# Le texte à analyser\\ntext = \\\"Symfony est un framework PHP. Symfony est utilisé dans de nombreux projects. PHP est un language puissant.\\\"\\n\\n# 1. Mettre en minuscules et supprimer la punctuation\\n# re.sub(r'[^\\\\w\\\\s]', '', ...) replace tout ce qui n'est pas un not ou un escape par rien.\\ntext_cleaned = re.sub(r'[^\\\\w\\\\s]', '', text.lower())\\n\\n# 2. Diviser le texte en une liste de mots\\nwords = text_cleaned.split()\\n\\n# 3. Compter les occurrences de chaque not\\nword_counts = Counter(words)\\n\\n# 4. Trier le dictionnaire par fréquence (la méthode most_common le fait par défaut)\\n# et le reconvertir en dictionnaire.\\nsorted_word_counts = dict(word_counts.most_common())\\n\\nprint(sorted_word_counts)"
+                        },
+                        "thought": true
+                    },
+                    {
+                        "codeExecutionResult": {
+                            "outcome": "OUTCOME_OK",
```
Comment (valtzu) [inline fixtures/Bridge/Gemini/code_execution_outcome_ok.json]: When I tried it via the API, after `codeExecutionResult.outcome: "OUTCOME_OK"` there is a normal `text` part, i.e.

```json
          {
            "text": "The 20th Fibonacci number is 6765.\n\nThe nearest palindrome to 6765 is 6776."
          }
```

Did you not get it in the response? If you did, let's add it to the fixture?

Comment (pentiminax) [reply fixtures/Bridge/Gemini/code_execution_outcome_ok.json]: It's weird, I never saw this part before, but you right I have it in API response, I will take this part into account.
I think `text` is not in the response when we have parts with `thoughts` key.

**Comment by pentiminax** [comment]
> First of all, thanks for working on this – when the `server_tools` were implemented, I only ever tested `google_search` and `url_context`.
> 
> In my opinion the output should not contain the generated & executed code by default, since the last message/`part` is a human readable message which already contains the answer to the asked question.
> 
> The `code_execution` is a server tool, like `google_search` or `url_context`, and those don't show up in the output either – even though f.e. search results / "sources" are available as `"grounding"` in the response.
> 
> If I'm building a customer-facing chat bot which should be able to answer to `Calculate 20th fibonacci number. Then find the nearest palindrome to it.` (an example from the `code_execution` docs), I don't think the customer should see the python code.
> 
> Somewhere we have this feature: `keepToolMessages`. Maybe we could even use that, or add a new one, like `keepServerToolParts` to control if those will be included or not 🤔

Thanks a lot for clarifying! I see your point now. Since `code_execution` is indeed just another server tool like `google_search `or `url_context`, it makes sense to treat it consistently and not expose the raw code by default. The final human-readable message is usually enough for the end user, while the tool details can stay in the background.

I like the idea of making this configurable.

**Comment by OskarStark** [comment]
The rebase looks wrong

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php [hunk 8]
```diff
@@ -110,21 +110,53 @@ private function convertStream(HttpResponse $result): \Generator
...
      *                 args: mixed[]
      *             },
-     *             text?: string
+     *             text?: string,
+     *             executableCode?: array{
+     *                 language?: string,
+     *                 code?: string
+     *             },
+     *             codeExecutionResult?: array{
+     *                 outcome: 'OUTCOME_OK'|'OUTCOME_FAILED'|'OUTCOME_DEADLINE_EXCEEDED',
```
Comment (OskarStark) [inline src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: Can we also have a fixture for OUTCOME_DEADLINE_EXCEEDED ?

Comment (pentiminax) [reply src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: Sure!

**Comment by pentiminax** [comment]
At the moment the code iterates through the contentParts array and looks for a successful code execution marker.

- Once a successful execution is detected, the flag $successfulCodeExecutionDetected is set to true.
- From that point onward, it concatenates any following text parts into the $content string.
- If any text was collected, it returns a TextResult containing that aggregated content.
- If no content was collected, it throws a RuntimeException("Code execution failed.").

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php [hunk 9]
```diff
@@ -110,24 +110,55 @@ private function convertStream(HttpResponse $result): \Generator
...
```
Comment (OskarStark) [inline src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: What about adding constants for these 3 strings?

Comment (pentiminax) [reply src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: A Dedicated enum like `Symfony\AI\Platform\Bridge\Gemini\Gemini\CodeExecutionResultOutcome` ?
Or directly in ResultConverter class ?

Comment (OskarStark) [reply src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: Constant in the result converter class is ok

Comment (pentiminax) [reply src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: Ok, done!

File: src/platform/src/Bridge/Gemini/Gemini/CodeExecutionResultOutcome.php [hunk 10]
```diff
@@ -0,0 +1,19 @@
...
+ * (c) Fabien Potencier <fabien@symfony.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Symfony\AI\Platform\Bridge\Gemini\Gemini;
+
+enum CodeExecutionResultOutcome: string
+{
```
Comment (OskarStark) [inline src/platform/src/Bridge/Gemini/Gemini/CodeExecutionResultOutcome.php]: You can add `Comparable` trait here

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php [hunk 11]
```diff
@@ -189,6 +189,6 @@ private function isSuccessfulCodeExecution(array $contentPart): bool
 
         $result = $contentPart['codeExecutionResult'];
 
-        return 'OUTCOME_OK' === $result['outcome'];
+        return CodeExecutionResultOutcome::OK->value === $result['outcome'];
```
Comment (OskarStark) [inline src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]:
```suggestion
        return CodeExecutionResultOutcome::from($result['outcome'])->equals(CodeExecutionResultOutcome::OK);
```
after using the Comparable trait

Comment (pentiminax) [reply src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]: I simply reverted and used constant in ResultConverter class

File: src/platform/src/Bridge/Gemini/Gemini/CodeExecutionResultOutcome.php (hunk 10 above)
Comment (pentiminax) [reply src/platform/src/Bridge/Gemini/Gemini/CodeExecutionResultOutcome.php]: I simply reverted and used constant in ResultConverter class

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php [hunk 12]
```diff
@@ -110,24 +114,55 @@ private function convertStream(HttpResponse $result): \Generator
...
      *                 args: mixed[]
      *             },
-     *             text?: string
+     *             text?: string,
+     *             executableCode?: array{
+     *                 language?: string,
+     *                 code?: string
+     *             },
+     *             codeExecutionResult?: array{
+     *                 outcome: 'OUTCOME_OK'|'OUTCOME_FAILED'|'OUTCOME_DEADLINE_EXCEEDED',
```
Comment (OskarStark) [inline src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]:
```suggestion
     *                 outcome: self::OUTCOME_*,
```

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php [hunk 13]
```diff
@@ -141,4 +176,23 @@ private function convertToolCall(array $toolCall): ToolCall
     {
         return new ToolCall($toolCall['id'] ?? '', $toolCall['name'], $toolCall['args']);
     }
+
+    /**
+     * @param array{
+     *     codeExecutionResult?: array{
+     *         outcome: 'OUTCOME_OK'|'OUTCOME_FAILED'|'OUTCOME_DEADLINE_EXCEEDED',
```
Comment (OskarStark) [inline src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]:
```suggestion
     *         outcome: self::OUTCOME_*,
```

**Review by OskarStark — APPROVED** [review]
Only one minor, afterwards good to merge. Thanks

File: src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php (hunk 12 above)
Comment (OskarStark) [inline src/platform/src/Bridge/Gemini/Gemini/ResultConverter.php]:
```suggestion
     *                 outcome: self::OUTCOME_*,
```

**Comment by OskarStark** [comment]
Thanks for fixing this bug @pentiminax.

**Comment by pentiminax** [comment]
Thanks for reviewing @OskarStark. 
I think we will have the same problem with Vertex bridge since it's Google models?

**Comment by OskarStark** [comment]
Yes, can you have a look?
